### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by mehrdad2** [ronack/anahita#4]
پس از ثبت سفارش ارور میده.

**Comment by mehrdad2** [comment]
به صورت تکی

**Comment by mehrdad2** [comment]
![screen shot 2017-05-24 at 10 53 57 am](https://cloud.githubusercontent.com/assets/4264683/26389501/7ba55c4e-406f-11e7-8b79-86505fcad92a.png)

**Comment by zmihamid** [comment]
مشکل حل شد
