### ISSUE TITLE
به چه طریق میتوان دسته بندی جدید اضافه کرد؟

### ISSUE THREAD

**Issue by mehrdad2** [ronack/anahita#5]
![screen shot 2017-05-24 at 10 59 22 am](https://cloud.githubusercontent.com/assets/4264683/26389635/230c0f00-4070-11e7-8821-76718d2eff55.png)

**Comment by mehrdad2** [comment]
دسته بندی به صورت داینامیک باشد

**Comment by zmihamid** [comment]
به داشبورد اضافه شد
